#!/bin/bash

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
#
# Job:		modified tor-buddy.sh script
# Author:	buddylove
# Web:		http://pirate-radio.eu
# Mail:		admin@pirate-radio.eu
# Forked:	http://learnnetsec.blogspot.com
# Usage:    ./torbuddy-ng
# Required:	see details in README.MD
#
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# --- variables --------------------------------------------------------------- #
DAEMON="/usr/bin/tor"
CHAINS="/etc/proxychains.conf"
CONFIGURATION="$(sudo tor --verify-config | grep 'Configuration was valid')"

function control_c {
echo -e "\n"
echo -e "[\e[0;33m INFO \e[0m]\e[0;37m\tShutting down tor...\e[0m"
sudo kill $(pgrep -x tor)
sleep 0.5
echo -e "[\e[0;32m  OK  \e[0m]\e[0;37m\tDone, I'm outta here\e[0m"
echo -e ""
exit $?
}

# --- script ------------------------------------------------------------------ #
		echo -e ""	
		echo -e "[\e[0;33m INFO \e[0m]\e[0;37m\tTo stop the script press CTRL+C\e[0m"
sleep 2
		echo -e "[\e[0;33m INFO \e[0m]\e[0;37m\tChecking if Tor is installed...\e[0m"

if [ -f "$DAEMON" ];
	then
		echo -e "[\e[0;32m  OK  \e[0m]\e[0;37m\tTor is Installed!\e[0m"
		echo -e "[\e[0;33m INFO \e[0m]\e[0;37m\tChecking for clean configuration\e[0m"

if [ -z "$CONFIGURATION" ];
	then
		echo -e "[\e[30;48;5;1m WARN \e[0m]\e[0;37m\tInvalid configuration. Check torrc file. Exiting\e[0m"
	exit 1

	fi

sleep 1
		echo -e "[\e[0;32m  OK  \e[0m]\e[0;37m\tConfiguration is clean\e[0m"
		echo -e "[\e[0;32m  OK  \e[0m]\e[0;37m\tStarting TOR...\e[0m"
		sudo tor --quiet;
else
		echo -e "[\e[30;48;5;1m WARN \e[0m]\e[0;37m\tTor isn't installed!\e[0m"
	    echo -e "[\e[0;33m INFO \e[0m]\e[0;37m\tTo install: apt-get update, then apt-get install tor\e[0m"
exit
fi
		echo -e "[\e[0;33m INFO \e[0m]\e[0;37m\tChecking if proxychains is installed...\e[0m"

if [ -f "$CHAINS" ];
	then
		echo -e "[\e[0;32m  OK  \e[0m]\e[0;37m\tProxychains is Installed!\e[0m"
	else
		echo -e "[\e[30;48;5;1m WARN \e[0m]\e[0;37m\tProxychains isn't installed!\e[0m"
		echo -e "[\e[0;33m INFO \e[0m]\e[0;37m\tTo install: apt-get update, then apt-get install proxychains\e[0m"
exit
fi

# loop
		echo -e ""	
		echo -e "[\e[0;32m  OK  \e[0m]\e[0;37m\tPlease enter how many seconds you want to grab a new IP: \c\e[0m"
trap control_c SIGINT
	read TIME

if [ "$TIME" -lt "30" ];
	then
		echo -e "[\e[0;33m INFO \e[0m]\e[0;37m\tWarning: Less than 30 seconds is not suggested!\e[0m"
		echo -e "[\e[0;32m  OK  \e[0m]\e[0;37m\tContinuing...\e[0m"
	else
		echo -e "[\e[0;32m  OK  \e[0m]\e[0;37m\tNameserver changes every $TIME seconds\e[0m"
		echo -e ""
		echo -e "[\e[0;33m INFO \e[0m]\e[0;37m\tCtrl-Z followed by bg to put script to background...\e[0m"
		echo -e ""
	fi

# Capture SIGINT (Ctrl-C) and exit
trap control_c SIGINT
for (( ; ; ))
do 
sleep "$TIME"
sudo kill $(pgrep -x tor)
sleep 0.2
sudo tor --quiet
echo -e "[\e[0;32m  OK  \e[0m]\e[0;37m\t$TIME seconds until next IP change\e[0m"
done

# END
