#!/bin/bash
# ----------------------------------------------------------------------------- #
# Job:		modified tor-buddy.sh script					#
# Author:	buddylove							#
# Web:		http://pirate-radio.eu						#
# Mail:		admin@pirate-radio.eu						#
# Forked:	http://learnnetsec.blogspot.com					#
# Required:	see details in README.MD					#
# ----------------------------------------------------------------------------- #

# --- variables --------------------------------------------------------------- #
DAEMON="/usr/bin/tor"
CHAINS="/etc/proxychains.conf"
CONFIGURATION="$(sudo tor --verify-config | grep 'Configuration was valid')"

# --- script ------------------------------------------------------------------ #
		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m	To stop the script press CTRL+C\e[0m"
sleep 2
		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m	Checking if Tor is installed...\e[0m"

if [ -f "$DAEMON" ];
	then
		echo -e "[\e[0;32mOK\e[0m]\e[0;37m	Tor is Installed!\e[0m"
		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m	Checking for clean configuration\e[0m"

if [ -z "$CONFIGURATION" ];
	then
		echo -e "[\e[30;48;5;1mWARN\e[0m]\e[0;37m	Invalid configuration. Check torrc file. Exiting\e[0m"
	exit 1

	fi

sleep 1
		echo -e "[\e[0;32mOK\e[0m]\e[0;37m	Configuration is clean\e[0m"
		echo -e "[\e[0;32mOK\e[0m]\e[0;37m	Starting TOR...\e[0m"
		sudo tor --quiet;
else
		echo -e "[\e[30;48;5;1mWARN\e[0m]\e[0;37m	Tor isn't installed!\e[0m"
	        echo -e "[\e[0;33mINFO\e[0m]\e[0;37m	To install: apt-get update, then apt-get install tor\e[0m"
exit
fi
		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m	Checking if proxychains is installed...\e[0m"

if [ -f "$CHAINS" ];
	then
		echo -e "[\e[0;32mOK\e[0m]\e[0;37m	Proxychains is Installed!\e[0m"
	else
		echo -e "[\e[30;48;5;1mWARN\e[0m]\e[0;37m	Proxychains isn't installed!\e[0m"
		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m	To install: apt-get update, then apt-get install proxychains\e[0m"
exit
fi

# loop
		echo -e "[\e[0;32mOK\e[0m]\e[0;37m	Please enter how many seconds you want to grab a new IP:\c\e[0m"
read TIME

if [ "$TIME" -lt "30" ];
	then
		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m	Warning: Less than 30 seconds is not suggested!\e[0m"
		echo -e "[\e[0;32mOK\e[0m]\e[0;37m	Continuing...\e[0m"
	else
		echo -e "[\e[0;32mOK\e[0m]\e[0;37m	Nameserver change every $TIME seconds\e[0m"
		echo -e "[\e[0;33mINFO\e[0m]\e[0;37m	Ctrl-Z followed by bg to put script to background...\e[0m"
	fi

function control_c {
echo -e "\n"
echo -e "[\e[0;33mINFO\e[0m]\e[0;37m	Shutting down tor...\e[0m"
sudo kill $(pgrep -x tor)
sleep 0.5
echo -e "[\e[0;32mOK\e[0m]\e[0;37m	Done, I'm outta here\e[0m"
exit $?
}
# Capture SIGINT (Ctrl-C) and exit
trap control_c SIGINT
for (( ; ; ))
do 
sleep "$TIME"
sudo kill $(pgrep -x tor)
sleep 0.5
sudo tor --quiet
echo -e "$TIME seconds until next IP change \n"
done

